name: build_Release
on:
  push:
    branches:
      - 2.0
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - 2.0
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  VERSION: '2.0.2'
 
jobs:
  build:
    runs-on: macos-13
    environment: Auto Build And Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Procursus
        uses: wwg135/procursus-action@main
        with:
          packages: ldid findutils sed coreutils make
          
      - name: Pre theos
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos        
     
      - name: Build and Install trustcache
        run: |
          set -x
          git clone https://github.com/CRKatri/trustcache
          cd trustcache
          gmake -j$(sysctl -n hw.physicalcpu) OPENSSL=1
          sudo cp trustcache /opt/procursus/bin/
          
      - name: Set env
        run: |
          sT=$(TZ=UTC-8 date +'%S')
          echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
          echo "shT=$(TZ=UTC-8 date +'%Y-%m-%d'' ''%H:%M:%S')" >> $GITHUB_ENV
          echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV
          
      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}
          echo ${{ env.shT }}
          echo ${{ env.logT }}
          
      - name: Build ipa
        run: |
          set -x
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A

          export THEOS=$HOME/theos
          gmake -j$(sysctl -n hw.physicalcpu)
          mv Dopamine/Dopamine.tipa Dopamine.ipa

      - name: Release Logs
        run: |
          set -x
          echo -e "更新时间：${{ env.logT }}" >> body.txt
          echo "" >> ./release.md
          echo -e "\n[点击普通版本下载](https://github.com/wwg135/Dopamine/releases/download/${{ env.msT }}/Dopamine.ipa)" >> ./release.md
          echo -e "\n[点击挂载版本下载](https://github.com/wwg135/Dopamine/releases/download/${{ env.msT }}/Dopamine_mount.ipa)" >> ./release.md
          echo -e "\n[点击KFD版本下载](https://github.com/wwg135/Dopamine/releases/download/${{ env.msT }}/KFDDopamine.ipa)" >> ./release.md

          cat body.txt > release.txt
          echo "" >> release.txt
          cat ./release.md >> release.txt
          
      - name: Release ipa
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.msT }}
          target_commitish: 2.0
          body_path: release.txt
          latest: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.ipa
